Repository ggurjar333/NFL-Stats, pull requests merged in 2023-12, with the labels that each got.

#6 Issue4
  src/sportsradar/extract/primaryfeeds.py
  src/test/unit/sportsradar/extract/primaryfeeds.py
Labels: enhancement

#18 Seasonal Statistics # issue17
  src/sportsradar/extract/teamfeeds.py
  test/unit/extract/teamfeeds.py
Labels: enhancement

#21 Issue14
  src/sportsradar/extract/additionalfeeds.py
  test/unit/extract/additionalfeeds.py
Labels: enhancement

#26 Implement Data Retrieval from Mongo DB
  src/sportsradar/workspace/datastore.py
Labels: enhancement

#29 Implementation of GameFeedsTransformer Class for Enhanced Data Processing
  src/sportsradar/transform/gamefeeds.py
  test/unit/transform/gamefeeds.py
Labels: enhancement

#34 Transform gamefeeds
  requirements.txt
  src/sportsradar/transform/classes.py
  src/sportsradar/transform/gamefeeds.py
  src/sportsradar/transform/params/__init__.py
  src/sportsradar/transform/params/gamefeeds.py
Labels: enhancement

#30 Issue14:
  src/sportsradar/extract/additionalfeeds.py
  test/unit/extract/additionalfeeds.py
Labels: bug, enhancement

#32 Issue23:Implement Data Extraction Operation for DraftFeeds - Draft Summary, Prospects, Team Draft Summary, Top Prospects
  src/sportsradar/extract/draftfeeds.py
  test/unit/extract/draftfeeds.py
Labels: enhancement

#33 Issue24:Implement Data Extraction Operation for TeamFeeds - Team Profile
  src/sportsradar/extract/teamfeeds.py
  test/unit/extract/teamfeeds.py
Labels: enhancement

#44 Add PlayerFeedsTransformer for Player Profile Data
  src/sportsradar/transform/params/playerfeeds.py
  src/sportsradar/transform/playerfeeds.py
  test/unit/transform/playerfeeds.py
Labels: enhancement, datacleaning

#45 TeamFeedsTransformer for Transforming Team Roster Data
  src/sportsradar/transform/params/teamfeeds.py
  src/sportsradar/transform/teamfeeds.py
  test/unit/transform/teamfeeds.py
Labels: enhancement, datacleaning

#47 Seasonal Statistics Transformation for TeamFeeds & Added Unit Tests
  src/sportsradar/transform/teamfeeds.py
  test/unit/transform/teamfeeds.py
Labels: enhancement, datacleaning

#50 Issue43:Implement Data Transform Operation for TeamFeeds - Team Profile
  src/sportsradar/transform/teamfeeds.py
  test/unit/transform/teamfeeds.py
Labels: enhancement

#54 Dev
  src/sportsradar/transform/additionalfeeds.py
  src/sportsradar/transform/draftfeeds.py
  src/sportsradar/transform/primaryfeeds.py
  src/sportsradar/transform/teamfeeds.py
  test/unit/transform/additionalfeeds.py
  test/unit/transform/draftfeeds.py
  test/unit/transform/primaryfeeds.py
  test/unit/transform/teamfeeds.py
Labels: enhancement

#56 Enhanced Resource Cache Efficiency and Flexibility with Environment Variables Support
  src/sportsradar/workspace/resource_cache.py
  test/unit/workspace/__init__.py
  test/unit/workspace/resource_cache.py
Labels: enhancement, data workspace

#58 Data Simulation - SportRadar
  notebooks/simulation.ipynb
  src/sportsradar/simulation/__init__.py
  src/sportsradar/simulation/available_recordings.py
  src/sportsradar/simulation/config.py
  src/sportsradar/simulation/gamefeeds.py
  src/sportsradar/simulation/session.py
  src/sportsradar/workspace/resource_cache.py
  test/unit/simulation/__init__.py
  test/unit/simulation/available_recordings.py
  test/unit/simulation/gamefeeds.py
  test/unit/simulation/session.py
  test/unit/workspace/__init__.py
  test/unit/workspace/resource_cache.py
Labels: enhancement, simulation
